# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea8f4ebf2f5eeca451d81ebed0a0a0a8e7d7970f6ac3c2cb8f342ffba9fbf438ab1f76346a7b82edf35de8de2174e0f8c05db31f7d31f2119dff097f1e6ff28

test:
  secret_key_base: 1a83b730d38c380ddf3fe9c121b1837f03f606d6c6fb8117722952b314d78afa5840a78df5b6fc356583c38f2248abe01e2d723a63479c4c4685a798dccb4cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
